spring:
  profiles:
    active: dev
seata:
  enabled: true
  application-id: cloud-storage-service
  tx-service-group: my_test_tx_group
  config:
    type: nacos
    file:
      name: file.conf
    nacos:
      serverAddr: 192.168.1.180:8848
      group: SEATA_GROUP
      userName: "nacos"
      password: "nacos"
      namespace:
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.1.180:8848
      namespace:
      userName: "nacos"
      password: "nacos"
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.yan.cloud.dao
  global-config:
    db-config:
      field-strategy: not-empty
      id-type: auto
      db-type: mysql
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    auto-mapping-unknown-column-behavior: none
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl