spring:
  profiles:
    active: dev
  redis:
    host: 192.168.5.122
    password: 123456
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 5
        max-wait: 5000
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000