server:
  port: 5501
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.40.199:3316/auth?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&autoReconnect=true&serverTimezone=UTC
    username: root
    password: 123456
    # 用来初始化数据库的，如果不存在表就自动创建
    initialization-mode: ALWAYS
    schema: classpath:ddl.sql
  redis:
    database: 0
    host: 192.168.40.199
    port: 6369
#  application:
#    name: cloud-order-service
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.40.199:8848
#ribbon:
#  ReadTimeout: 600000
#  ConnectTimeout: 600000
logging:
  level:
    org:
      springframework:
        security: INFO
# 配置已在 Oauth2AuthorizationServerConfig 中配置
#security:
#  oauth2:
#    authorization:
#      # 允许使用 /oauth/check_token
#      check-token-access: isAuthenticated()
#    client:
#      # 客户端注册的 回调地址 当客户端或应用 第一步获取授权码的时候会带一个回调地址
#      # 因为你传递过来的回调地址授权服务器不知道是否合法，可能会在传输的中途被篡改，
#      # 所以在授权服务器里面需要你注册一个回调地址，与你传递过来的进行对比，
#      # 如果匹配才会携带授权码进行回调
#      registered-redirect-uri: http://example.com
#      # 客户端ID 和 密钥
#      client-id: yanApp
#      client-secret: yanApp123
#      # 客户端授权范围
#      scope: all
#      # token 有效期
#      access-token-validity-seconds: 6000
#      # 刷新 token 的有效期
#      refresh-token-validity-seconds: 6000
#      # 允许的授权类型：授权码模式，密码模式
#      grant-type: authorization_code, password
#      # 可以访问资源的 ID
#      resource-ids: res1
#    # 集合类型可以多个，如果客户端可以访问的资源服务器ID不再他的范围就无法访问响应资源
#    resource:
#      id: res1

mybatis-plus:
  #  datasource: dataSource
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package:  com.yan.cloud.pojo
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID", 4:"该类型为未设置主键类型", 5:"字符串全局唯一ID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  configuration-properties:
    #设置全局属性用于控制数据库的类型
    dbType: mysql