spring:
  profiles:
    active: dev
  application:
    name: cloud-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.42.201:8848
    alibaba:
      seata:
        tx-service-group: my_seata_tx_group
feign:
  hystrix:
    enabled: false
logging:
  level:
    io:
      seata: info
