server:
  port: 2001
spring:
  profiles:
    active: dev
  application:
    name: cloud-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.40.199:8848
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
